# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/generator_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  logging:
    level: debug
  resources:
    static-locations: classpath:/
  mvc:
    static-path-pattern: /**
# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

server:
  servlet:
    context-path: /

