# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/generator_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://mysql.dev.victorplus.cn:3306/boss-finance?characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
    username: accountuser
    password: 1cM7J4ii8pKTnNACtN
  logging:
    level: debug
  resources:
    static-locations: classpath:/,classpath:/view/
  mvc:
    static-path-pattern: /**
# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

server:
  servlet:
    context-path: /

